version: '3.8'

services:
  tg_news:
    build: .
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./my_bot.session:/app/my_bot.session
      - ./my_userbot.session:/app/my_userbot.session
      - ./logs:/app/logs