version: '3.8'

services:
  tg_news:
    image: resistordocker/tg_news_aggregator
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./my_bot.session:/app/my_bot.session
      - ./my_userbot.session:/app/my_userbot.session
      - ./logs:/app/logs
      - ./users/users_settings.json:/app/users/users_settings.json